resources:
  - name: node-app
    type: git
    source:
      uri: git@github.com:iranda/node-app.git
      branch: master
      access_token: ((github-access-token))
      private_key: ((github-private-key))
  - name: cf-dev-server
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-dev-space))

jobs:
  - name: deploy-cf-node-app
    plan:
      - get: node-app
      - task: build
        file: node-app/ci/tasks/build.yml
      - put: cf-dev-server
        params:
          manifest: node-app/ci/manifest_dev.yml
          path: build
          current_app_name: savanta-development
          environment_variables:
            ACCESS_KEY_ID: ((aws-acess-key-id))
            SECRET_ACCESS_KEY: ((aws-access-key))
            EGNYTE_API_KEY: ((egnyte-api-key))
            EGNYTE_TOKEN: ((egnyte-token))
            EGNYTE_WEBSITE: https://savanta.egnyte.com
